export const DISTRICTS={Thanjavur:{lat:10.787,lon:79.1378,market:'Thanjavur Mandi'},Erode:{lat:11.341,lon:77.7172,market:'Perundurai Erode APMC'},Salem:{lat:11.6643,lon:78.146,market:'Shevapet Mandi'},Madurai:{lat:9.9252,lon:78.1198,market:'Mattuthavani Mandi'},Coimbatore:{lat:11.0168,lon:76.9558,market:'Mettupalayam APMC'},Tiruchirappalli:{lat:10.7905,lon:78.7047,market:'Gandhi Market'},Cuddalore:{lat:11.748,lon:79.7714,market:'Virudhachalam APMC'},Tirunelveli:{lat:8.7139,lon:77.7567,market:'Tirunelveli Mandi'},Dharmapuri:{lat:12.1211,lon:78.1582,market:'Dharmapuri Mandi'},Tiruvarur:{lat:10.7725,lon:79.6365,market:'Mannargudi Mandi'},Villupuram:{lat:11.9401,lon:79.4861,market:'Villupuram Mandi'},Dindigul:{lat:10.3673,lon:77.9803,market:'Oddanchatram Market'}};

export const CROPS=[
{id:'paddy',ta:'நெல்',en:'Paddy (Rice)',soils:['clay','alluvial','black'],water:['sufficient','canal','borewell'],budget:24000,days:120,yield:'22–28 bags',price:'₹1,450–₹1,720',reasonTa:'களிமண் மற்றும் வண்டல் மண், நிலையான பாசனம் உள்ள நிலங்களுக்கு ஏற்றது.',reasonEn:'Good for clay/alluvial soils with reliable irrigation.',calendar:[[1,'நாற்று தயாரிப்பு','Nursery & seed treatment'],[22,'நாற்று நடுதல்','Transplanting'],[45,'களை எடுத்தல் & உரமிடுதல்','Weeding & top dressing'],[75,'மணி உருவாதல்','Panicle emergence'],[95,'பால் பிடிக்கும் நிலை','Milking stage'],[120,'அறுவடை','Harvest']]},
{id:'groundnut',ta:'நிலக்கடலை',en:'Groundnut (Peanut)',soils:['red','sandy'],water:['limited','rainfed','borewell'],budget:18000,days:105,yield:'14–18 bags',price:'₹6,400–₹7,300',reasonTa:'செம்மண்/மணல் மண் மற்றும் குறைந்த நீர் வசதிக்கு ஏற்றது.',reasonEn:'Suitable for red/sandy soils and limited water.',calendar:[[1,'விதைப்பு','Sowing'],[20,'முதல் களை எடுத்தல்','First weeding'],[35,'உரமிடுதல்','Nutrient application'],[60,'பூக்கும் நிலை','Flowering'],[85,'காய் உருவாதல்','Pegging & pod formation'],[105,'அறுவடை','Harvest']]},
{id:'maize',ta:'மக்காச்சோளம்',en:'Maize',soils:['red','black','alluvial'],water:['limited','sufficient','borewell'],budget:20000,days:100,yield:'20–25 quintals',price:'₹2,100–₹2,500/q',reasonTa:'செம்மண், கரிசல் மற்றும் வண்டல் மண்ணில் நல்ல வளர்ச்சி.',reasonEn:'Performs well in red, black and alluvial soils.',calendar:[[1,'விதைப்பு','Sowing'],[15,'முளை பராமரிப்பு','Early crop care'],[35,'மேல் உரம்','Top dressing'],[55,'களை கட்டுப்பாடு','Weed control'],[75,'கதிர் உருவாதல்','Tasseling'],[100,'அறுவடை','Harvest']]},
{id:'cotton',ta:'பருத்தி',en:'Cotton',soils:['black','red'],water:['limited','sufficient','borewell'],budget:26000,days:170,yield:'8–12 quintals',price:'₹6,800–₹7,500/q',reasonTa:'கரிசல் மண் மற்றும் மிதமான நீர் வசதிக்கு ஏற்றது.',reasonEn:'Best suited to black soil with moderate water.',calendar:[[1,'விதைப்பு','Sowing'],[30,'களை கட்டுப்பாடு','Weed control'],[60,'மேல் உரம்','Top dressing'],[90,'பூக்கும் நிலை','Flowering'],[130,'காய் வெடிப்பு','Boll development'],[170,'அறுவடை','Picking']]},
{id:'tomato',ta:'தக்காளி',en:'Tomato',soils:['red','alluvial'],water:['sufficient','borewell','openWell'],budget:35000,days:90,yield:'12–18 tonnes',price:'₹1,500–₹3,500/q',reasonTa:'நல்ல வடிகால் மற்றும் தொடர்ச்சியான நீர் வசதி உள்ள நிலங்களுக்கு ஏற்றது.',reasonEn:'Needs good drainage and regular irrigation.',calendar:[[1,'நாற்று நடுதல்','Transplanting'],[20,'வளர்ச்சி உரம்','Vegetative nutrition'],[40,'பூக்கும் நிலை','Flowering'],[55,'காய் உருவாதல்','Fruit setting'],[70,'முதல் பறிப்பு','First picking'],[90,'தொடர் அறுவடை','Harvesting']]}
];

export const SOILS=[['red','செம்மண்','Red Soil'],['black','கரிசல் மண்','Black Soil'],['alluvial','வண்டல் மண்','Alluvial Soil'],['clay','களிமண்','Clay Soil'],['sandy','மணல் மண்','Sandy Soil']];
export const WATER=[['rainfed','மழைநீர்','Rainfed'],['limited','குறைந்த நீர்','Limited water'],['sufficient','போதுமான நீர்','Sufficient water'],['borewell','ஆழ்துளை கிணறு','Borewell'],['canal','கால்வாய்','Canal'],['openWell','கிணறு','Open well']];
export const STATES=['Tamil Nadu','Karnataka','Kerala','Andhra Pradesh','Telangana','Other'];
